<?php
	require_once 'Commando\Argument.php';

	/**
	 * Test class for Commando_Argument.
	 * Generated by PHPUnit on 2011-02-11 at 12:55:26.
	 */
	class Commando_ArgumentTest extends PHPUnit_Framework_TestCase {
		/**
		 * @var Commando_Argument
		 */
		protected $object;

		/**
		 * Sets up the fixture, for example, opens a network connection.
		 * This method is called before a test is executed.
		 */
		protected function setUp() {
			$this->object = null;
		}

		/**
		 * Tears down the fixture, for example, closes a network connection.
		 * This method is called after a test is executed.
		 */
		protected function tearDown() {
		}

		/**
		 * @todo Implement testFactory().
		 */
		public function testFactory() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testGetTitle().
		 */
		public function testGetTitle() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testGetDescription().
		 */
		public function testGetDescription() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testIsRequired().
		 */
		public function testIsRequired() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testStripSwitch().
		 */
		public function testStripSwitch() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testIsValid().
		 */
		public function testIsValid() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testBindPossibleArgumentValues().
		 */
		public function testBindPossibleArgumentValues() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testValidate().
		 */
		public function testValidate() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testAddValue().
		 */
		public function testAddValue() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement test__toString().
		 */
		public function test__toString() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}
	}