<?php
	require_once 'Commando\Subject.php';

	/**
	 * Test class for Commando_Subject.
	 * Generated by PHPUnit on 2011-02-11 at 14:26:33.
	 */
	class Commando_SubjectTest extends PHPUnit_Framework_TestCase {
		/**
		 * @var Commando_Subject
		 */
		protected $object;

		/**
		 * Sets up the fixture, for example, opens a network connection.
		 * This method is called before a test is executed.
		 */
		protected function setUp() {
			$this->object = null;
		}

		/**
		 * Tears down the fixture, for example, closes a network connection.
		 * This method is called after a test is executed.
		 */
		protected function tearDown() {
		}

		/**
		 * @todo Implement testAttach().
		 */
		public function testAttach() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testDetach().
		 */
		public function testDetach() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testNotify().
		 */
		public function testNotify() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}
	}