<?php
	require_once 'Commando.php';

	/**
	 * Test class for Commando.
	 * Generated by PHPUnit on 2011-02-11 at 12:51:50.
	 */
	class CommandoTest extends PHPUnit_Framework_TestCase {
		/**
		 * @var Commando
		 */
		protected $object;

		/**
		 * Sets up the fixture, for example, opens a network connection.
		 * This method is called before a test is executed.
		 */
		protected function setUp() {
			$this->object = new Commando;
		}

		/**
		 * Tears down the fixture, for example, closes a network connection.
		 * This method is called after a test is executed.
		 */
		protected function tearDown() {
		}

		/**
		 * @todo Implement testSingleton().
		 */
		public function testSingleton() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testConfig().
		 */
		public function testConfig() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testAddArgument().
		 */
		public function testAddArgument() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testIsCli().
		 */
		public function testIsCli() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testShowHelp().
		 */
		public function testShowHelp() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testValidate().
		 */
		public function testValidate() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testExecute().
		 */
		public function testExecute() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement test__toString().
		 */
		public function test__toString() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}
	}