<?php
	require_once 'Commando\Argument\Value.php';

	/**
	 * Test class for Commando_Argument_Value.
	 * Generated by PHPUnit on 2011-02-11 at 14:12:22.
	 */
	class Commando_Argument_ValueTest extends PHPUnit_Framework_TestCase {
		/**
		 * @var Commando_Argument_Value
		 */
		protected $object;

		/**
		 * Sets up the fixture, for example, opens a network connection.
		 * This method is called before a test is executed.
		 */
		protected function setUp() {
			$this->object = null;
		}

		/**
		 * Tears down the fixture, for example, closes a network connection.
		 * This method is called after a test is executed.
		 */
		protected function tearDown() {
		}

		/**
		 * @todo Implement testFactory().
		 */
		public function testFactory() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testIsRequired().
		 */
		public function testIsRequired() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testHasValue().
		 */
		public function testHasValue() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testIsMaster().
		 */
		public function testIsMaster() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testIsValid().
		 */
		public function testIsValid() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testSetValue().
		 */
		public function testSetValue() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement testGetValue().
		 */
		public function testGetValue() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}

		/**
		 * @todo Implement test__toString().
		 */
		public function test__toString() {
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}
	}